import Head from 'next/head'
// import Avatar from '@material-ui/core/Avatar';
import Image from 'next/image'
import profilePic from '../public/me.jpg'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import GitHubIcon from '@material-ui/icons/GitHub'
import LinkedInIcon from '@material-ui/icons/LinkedIn'
import EmailIcon from '@material-ui/icons/Email'
import DescriptionIcon from '@material-ui/icons/Description'
import KeyboardArrowDownIcon from '@material-ui/icons/KeyboardArrowDown'
import React from 'react'
import Card from 'react-bootstrap/Card'
import CardDeck from 'react-bootstrap/CardDeck'
// import {Container, Row, Col} from 'react-bootstrap'
import about from './About'
import project from './Project'
import Navbar from "./Navbar"
import Section from "./Section"
import nw from '../public/nw.jpg'
import mm from '../public/mm.jpeg'
import f from '../public/f.jpeg'

export default function Home () {
    return (
      <div>
        <div>
        <div className={styles.container}>
      <Head>
        <title>Ariana Nesbit</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
        <div className={styles.links}>
         
          <Navbar />
          <Section
            title=''
            dark={true}
            id='Home'
          />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello
        </h1>
        <Image className={styles.profilePic} src={profilePic} alt='Ariana'/>
        <h2>I'm Ariana Nesbit, a full stack developer</h2>
        <br />
        <br />

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}
        
        <KeyboardArrowDownIcon />       
        <br />
        <br />

        <Section
          title='About Me'
          dark={false}
          id="About"
        />
        <div className={styles.aboutContainer} id='About'>
            {/* <main className={styles.aboutMain}> */}
        <div className={styles.aboutHeader}>
            <h2>I'm a full stack engineer who wants to make a difference in the world</h2>
            <h3>through thoughtful code and design.  I enjoy coding and working to be a better me each day. <br />  
                In my free time, you can find me in the mountains, looking for animals to pet, or in my garden.</h3>
            </div>
            <div className ={styles.listContainer}>
            {/* <div className={styles.languages}> */}
            <ul className={styles.languages}>
                <p><strong>Languages</strong></p>
                <li>HTML</li>
                <li>CSS</li>
                <li>SQL</li>
                <li>Python</li>
                <li>JavaScript</li>
                <li>TypeScript</li>
                <br />
                <br />
            </ul>
            {/* </div>  */}
            
            {/* <div className={styles.databases}> */}
            <ul className={styles.databases}>
                <p><strong>Databases</strong></p>
                <li>PostgreSQL</li>
                <li>MongoDB</li>
                <li>Mongoose</li>
                <li>SQLAlchemy</li>
                <li>Sequelize</li>
                <br />
                <br />
                <br />
            </ul>
            {/* </div> */}
            
            {/* <div className={styles.librariesFrameworks}> */}
                <ul className={styles.librariesFrameworks}>
                <p><strong>Libraries / Frameworks</strong></p>
                <li>React</li>
                <li>Next.js</li>
                <li>Node.js</li>
                <li>Express.js</li>
                <li>Material-UI</li>
                <li>Styled-Components</li>
                <li>Bootstrap</li>
                <li>Flask</li>
                </ul>
            {/* </div> */}

            {/* <div className={styles.other}> */}
                <ul className={styles.other}>
                    <p><strong>Other</strong></p>
                    <li>RESTful Routing</li>
                    <li>JSON</li>
                    <li>APIs</li>
                    <li>EJS</li>
                    <li>Github</li>
                    <li>Netlify</li>
                    <li>Heroku</li>
                    <br />
                </ul>
            {/* </div> */}
        </div>
        <Section
          title='My Projects'
          subtitle={project}
          dark={true}
          id="Project"
        />
        {/* <div id='Projects'>
        <div className={styles.projectContainer}> */}
        <div className={styles.cards}>
  <CardDeck>
    <div className={styles.cardOne}>
  <Card>
    <Card.Img variant='top' src='nw.jpg' width='100px' height='200px'/>
    <Card.Body>
      {/* <Card.Title>Nature Walk</Card.Title> */}
      <Card.Text>
        A scenario-based game that monitors players' health based on their choices
        <br/>
        <br/>
      </Card.Text>
    </Card.Body>
    <Card.Footer>
    <Card.Link href='/One'>Nature Walk</Card.Link>
      <small className='text-muted'> | HTML, CSS, JavaScript</small>
    </Card.Footer>
  </Card>
  </div>
  </CardDeck>

  <CardDeck>
    <div className={styles.cardTwo}>
  <Card>
    <Card.Img variant='top' src='mm.jpeg' width='100px' height='200px'/>
    <Card.Body>
      <Card.Text>
        A full stack app that allows users to locate their closest farmers market using the USDA National Farmers Market Directory API
      </Card.Text>
    </Card.Body>
    <Card.Footer>
    <Card.Link href='/One'>Market Match</Card.Link>
      <small className='text-muted'> | Express, Node.js, Sequelize, EJS</small>
    </Card.Footer>
  </Card>
  </div>
  </CardDeck>

  <CardDeck>
    <div className={styles.cardThree}>
  <Card>
    <Card.Img variant='top' src='f.jpeg' width='100px' height='200px'/>
    <Card.Body>
      <Card.Text>
      A MERN stack application built to allow families to better coordinate their schedules via calendar
      <br />
      <br />
      </Card.Text>
    </Card.Body>
    <Card.Footer>
    <Card.Link href='/One'>Falendar</Card.Link>
      <small className='text-muted'> | Express, MongoDB, Mongoose, React, CSS</small>
    </Card.Footer>
  </Card>
  </div>
  </CardDeck>
  </div>
{/* </div> */}
            {/* <div className={styles.natureWalk}>
                <h2>Nature Walk</h2>
                <Image src={nw} className={styles.nw} width='400px' height='200px' alt='Trees during Fall'/>
            </div>
            
            <div className={styles.marketMatch}>
                <h2>Market Match</h2>
                <Image src={mm} className={styles.mm} width='400px' height='200px' alt='Fresh fruits and veggies'/>
            </div>

            <div className={styles.falendar}>
                <h2>Falendar</h2>
                <Image src={f} className={styles.f} width='400px' height='200px' alt='Calendar'/>
            </div>
            </div>
        </div> */}
     
{/*   
<div className={styles.container}>
      <Head>
        <title>Ariana Nesbit</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      {/* </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello
        </h1>
        <Image className={styles.profilePic} src={profilePic} alt='Ariana'/>
        <h2>I'm Ariana Nesbit, a full stack developer...</h2>
        <h3>Welcome to My Portfolio</h3> */}

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}
        {/* <Link href="/about">
          <a><KeyboardArrowDownIcon /></a>
        </Link>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />

      <div className='downArrow'>
      <div className='bounce'>
        <KeyboardArrowDownIcon />
        <a href= '/about' /> 
        </div> */}
      {/* </div>  */}
      
      </div>
   
    </main>
    </div>
    </div>
    </div>
    

      


<div>
      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        > */}
        <div className = 'github'>
          <GitHubIcon />
              <p>nesbita</p>
        </div>
        
        <div className = 'linkedIn'>
          <LinkedInIcon />
            <p>ariananesbit</p>
        </div>

        <div className = 'email'>
          <EmailIcon/>
              <p>ariananesbit@gmail.com</p>
        </div>

        <div className = 'resume'>
          <DescriptionIcon />
              <p>Resume</p>
        </div>

          {/* Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        {/* </a> */}
      </footer>
</div>
    </div>
    
    
    


      


      
      
)
}